############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.wapiti.domain.entity         # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件


############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.wapiti.my.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
