############################################################
#
# 用户微服务
# web访问端口号  约定：8003
#
############################################################
server:
  port: 5289
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可


spring:
  datasource:                                         # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql驱动
    url: jdbc:mysql://rm-wz930n2g76vwae90kzo.mysql.rds.aliyuncs.com:3306/wapiti?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true&usesSSL=false
    username: sue_mysql_s
    password: ShuShun1558
    hikari:
      connection-timeout: 1800000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  redis:
    database: 0
    host: r-wz9fsujq683okec4zapd.redis.rds.aliyuncs.com
    port: 6379
    password: ShuShun1558
#    client-name: r-wz9fsujq683okec4za
